### PR TITLE
feat: add setAppliedTags to new DJs app

### PR DESCRIPTION
**Pull request by lyledouglass**
Added an extra step to the DJs App auto-mention to apply the 'Pending'
tag to the post

### CODE REVIEW

**Comment by lyledouglass** [comment]
Admittedly I have no clue if discord.js allows strings in this method, the docs aren't super clear on it

**Comment by lyledouglass** [comment]
Digging in a bit more I don't think a string will work - will look into this a bit more

**Comment by lyledouglass** [comment]
Think this should work - will need to test it out!

**Comment by waggz81** [comment]
thinking about this it should probably be added to the config for future expansion. there doesn't seem to be an easy way to retrieve tags in the client so we could still roll with the tag name and the same code but pull the string from the config, and as an array rather than a single tag.

**Pull request merged**
